package ru.otus.otuskotlin.propertysale.be.common.models.common

enum class PsStubCase {
    NONE,

    FLAT_LIST_SUCCESS,
    FLAT_CREATE_SUCCESS,
    FLAT_READ_SUCCESS,
    FLAT_UPDATE_SUCCESS,
    FLAT_DELETE_SUCCESS,
    FLAT_OFFERS_SUCCESS,

    HOUSE_LIST_SUCCESS,
    HOUSE_CREATE_SUCCESS,
    HOUSE_READ_SUCCESS,
    HOUSE_UPDATE_SUCCESS,
    HOUSE_DELETE_SUCCESS,
    HOUSE_OFFERS_SUCCESS,

    ROOM_LIST_SUCCESS,
    ROOM_CREATE_SUCCESS,
    ROOM_READ_SUCCESS,
    ROOM_UPDATE_SUCCESS,
    ROOM_DELETE_SUCCESS,
    ROOM_OFFERS_SUCCESS,
}
