POST http://{{url}}/flat/list
Content-Type: application/json

{
  "type": "PsRequestFlatList",
  "debug": {
    "stubCase": "SUCCESS"
  }
}

###
POST http://{{url}}/flat/create
Content-Type: application/json

{
  "type": "PsRequestFlatCreate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "createData": {
    "name": "Test Flat",
    "description": "Test Flat Description",
    "floor": 5,
    "numberOfRooms": 2
  }
}

###
POST http://{{url}}/flat/read
Content-Type: application/json

{
  "type": "PsRequestFlatRead",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "flatId": "test-flat-id"
}

###
POST http://{{url}}/flat/update
Content-Type: application/json

{
  "type": "PsRequestFlatUpdate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "updateData": {
    "id": "test-flat-id",
    "name": "Test Flat updated",
    "description": "Test Flat Description updated",
    "floor": 3,
    "numberOfRooms": 1
  }
}

###
POST http://{{url}}/flat/delete
Content-Type: application/json

{
  "type": "PsRequestFlatDelete",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "flatId": "test-flat-id"
}

###
