POST http://{{url}}/house/list
Content-Type: application/json

{
  "type": "PsRequestHouseList",
  "debug": {
    "stubCase": "SUCCESS"
  }
}

###
POST http://{{url}}/house/create
Content-Type: application/json

{
  "type": "PsRequestHouseCreate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "createData": {
    "name": "Test House",
    "description": "Test House Description",
    "floor": 5,
    "numberOfRooms": 2
  }
}

###
POST http://{{url}}/house/read
Content-Type: application/json

{
  "type": "PsRequestHouseRead",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "houseId": "test-house-id"
}

###
POST http://{{url}}/house/update
Content-Type: application/json

{
  "type": "PsRequestHouseUpdate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "updateData": {
    "id": "test-house-id",
    "name": "Test House updated",
    "description": "Test House Description updated",
    "floor": 3,
    "numberOfRooms": 1
  }
}

###
POST http://{{url}}/house/delete
Content-Type: application/json

{
  "type": "PsRequestHouseDelete",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "houseId": "test-house-id"
}

###
