POST http://{{url}}/room/list
Content-Type: application/json

{
  "type": "PsRequestRoomList",
  "debug": {
    "stubCase": "SUCCESS"
  }
}

###
POST http://{{url}}/room/create
Content-Type: application/json

{
  "type": "PsRequestRoomCreate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "createData": {
    "name": "Test Room",
    "description": "Test Room Description",
    "floor": 5,
    "numberOfRooms": 2
  }
}

###
POST http://{{url}}/room/read
Content-Type: application/json

{
  "type": "PsRequestRoomRead",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "roomId": "test-room-id"
}

###
POST http://{{url}}/room/update
Content-Type: application/json

{
  "type": "PsRequestRoomUpdate",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "updateData": {
    "id": "test-room-id",
    "name": "Test Room updated",
    "description": "Test Room Description updated",
    "floor": 3,
    "numberOfRooms": 1
  }
}

###
POST http://{{url}}/room/delete
Content-Type: application/json

{
  "type": "PsRequestRoomDelete",
  "debug": {
    "stubCase": "SUCCESS"
  },
  "roomId": "test-room-id"
}

###
